language: cpp
os: osx
before_install:
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt glm; fi
- if [ $TRAVIS_OS_NAME == osx ]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi
script:
- if [ $TRAVIS_OS_NAME == osx ]; then mkdir build && cd build && cmake .. && make -j3; fi
- if [ $TRAVIS_OS_NAME == osx ]; then macdeployqt Nome.app; fi
