version: 0.1.{build}
image: Visual Studio 2017
shallow_clone: true

install:
- cmd: >-
    set PATH=C:\Qt\5.10\msvc2017_64\bin;%PATH%

    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    vcpkg install glm:x64-windows

build_script:
- cmd: >-
    md build-appveyor
    
    cd build-appveyor
    
    cmake .. -G "NMake Makefiles" -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install
    
    type CMakeCache.txt
    
    cmake --build .
    
    cmake --build . --target install
    
    cd ..

after_build:
- cmd: windeployqt %APPVEYOR_BUILD_FOLDER%\install
- cmd: del /f %APPVEYOR_BUILD_FOLDER%\install\opengl32sw.dll
- cmd: 7z a Nome-win64-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\install
- cmd: 7z rn Nome-win64-%APPVEYOR_BUILD_VERSION%.zip install Nome-%APPVEYOR_BUILD_VERSION%

artifacts:
- path: Nome-win64-%APPVEYOR_BUILD_VERSION%.zip
  name: Nome
