#line 2 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
static yyconst short int yy_acclist[310] =
    {   0,
       56,   55,   54,   55,   55,   55,   52,   55,   53,   55,
       55,   55,    5,   55,   51,   55,   51,   55,   51,   55,
       51,   55,   51,   55,   51,   55,   51,   55,   51,   55,
       51,   55,   51,   55,   51,   55,   51,   55,   51,   55,
       51,   55,   49,   55,   50,   55,    4,   55,    4,   55,
       54,    1,    1,    2,    5,    5,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,    3,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   11,   51,   51,   10,   51,   51,   51,   51,

       51,   51,   51,   51,   20,   51,   51,   51,   51,   51,
       51,   51,    6,    6,   18,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
        7,   51,   21,   51,   51,   51,   51,   25,   51,   51,
       51,   51,   51,   51,   51,   51,   12,   51,   51,   51,
       51,   51,   48,   51,    6,    6,    6,   51,   16,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   43,   51,   51,   51,   51,
       51,   15,   51,   51,   51,   34,   51,   51,   51,   51,
       51,   32,   51,   41,   51,   51,   51,   51,   51,   51,

       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       29,   51,   51,   40,   51,   23,   51,    8,   51,   51,
       39,   51,   51,   51,   51,   27,   51,   19,   51,   51,
       51,   22,   51,   51,   51,   51,   26,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   13,   51,
       51,   51,   51,   51,   44,   51,   51,   51,   51,   17,
       51,   51,   51,   51,   51,   36,   51,   31,   51,   51,
       51,   33,   51,   42,   51,   30,   51,   51,   24,   51,
        9,   51,   51,   51,   51,   28,   51,   51,   38,   51,
       51,   51,   51,   14,   51,   51,   37,   51,   35,   51,

       51,   45,   51,   51,   47,   51,   51,   46,   51
    } ;

static yyconst short int yy_accept[256] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    5,    6,    7,
        9,   11,   12,   13,   15,   17,   19,   21,   23,   25,
       27,   29,   31,   33,   35,   37,   39,   41,   43,   45,
       47,   49,   51,   52,   53,   54,   54,   55,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
       77,   78,   79,   80,   81,   82,   83,   83,   83,   84,
       85,   86,   87,   88,   89,   90,   91,   92,   93,   95,
       96,   98,   99,  100,  101,  102,  103,  104,  105,  107,
      108,  109,  110,  111,  112,  113,  114,  115,  117,  118,

      119,  120,  121,  122,  123,  124,  125,  126,  127,  128,
      129,  130,  131,  133,  135,  136,  137,  138,  140,  141,
      142,  143,  144,  145,  146,  147,  149,  150,  151,  152,
      153,  155,  156,  157,  158,  159,  161,  162,  163,  164,
      165,  166,  167,  168,  169,  170,  171,  172,  173,  174,
      175,  176,  178,  179,  180,  181,  182,  184,  185,  186,
      188,  189,  190,  191,  192,  194,  196,  197,  198,  199,
      200,  201,  202,  203,  204,  205,  206,  207,  208,  209,
      210,  211,  213,  214,  216,  218,  220,  221,  223,  224,
      225,  226,  228,  230,  231,  232,  234,  235,  236,  237,

      239,  240,  241,  242,  243,  244,  245,  246,  247,  248,
      249,  251,  252,  253,  254,  255,  257,  258,  259,  260,
      262,  263,  264,  265,  266,  268,  270,  271,  272,  274,
      276,  278,  279,  281,  283,  284,  285,  286,  288,  289,
      291,  292,  293,  294,  296,  297,  299,  301,  302,  304,
      305,  307,  308,  310,  310
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    1,    1,    1,    6,
        7,    8,    9,    1,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
        1,    1,    1,    1,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,    1,    1,    1,   13,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   12,   30,   31,   32,   33,   34,   12,   35,
       36,   12,   37,    1,   38,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[39] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        4,    5,    3,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1
    } ;

static yyconst short int yy_base[264] =
    {   0,
        0,    0,   36,   37,  344,  345,   39,  340,    0,  334,
      345,   36,  330,   38,    0,  326,   28,  321,   16,   38,
      308,  310,   39,   39,  308,  307,   44,   33,  345,  345,
      345,  327,   62,  330,  345,   77,  345,  321,   57,  320,
        0,  303,  299,  303,  302,  309,  296,  308,  296,  294,
      290,  285,  288,   43,  295,  298,   50,  284,  301,  282,
      295,   44,  298,  284,  281,  345,    0,  115,  285,  292,
      279,  288,  139,  275,  286,  276,  269,  269,    0,  279,
        0,  269,  280,  266,  269,  259,  280,  268,    0,  263,
      274,  271,  262,  261,  269,    0,  171,    0,  261,  255,

      252,  269,  260,  263,   66,  250,  252,  260,   73,  246,
      234,  229,    0,    0,  227,  215,  229,    0,  214,  225,
      222,  207,  213,  205,  218,    0,  213,  220,  202,  214,
        0,    0,  209,    0,  213,    0,  212,  202,  198,  202,
      210,  198,  196,  192,  190,  189,  188,   69,   74,  179,
      180,    0,  177,  173,  170,  169,    0,  178,  181,    0,
      164,  181,  171,  170,    0,    0,  170,  177,  174,  173,
      163,  156,  156,  166,  168,  154,  156,  138,  152,  147,
      137,    0,  147,    0,    0,    0,  135,    0,  138,  139,
      137,    0,    0,  125,  117,    0,  130,  118,  132,    0,

      129,  126,  111,  117,  119,  126,  121,  120,  119,  105,
        0,  103,  116,  115,  107,    0,  104,   98,   97,    0,
      105,   84,   97,   87,    0,    0,   89,   92,    0,    0,
        0,   93,    0,    0,   81,   85,   88,    0,   77,    0,
       85,   84,   70,    0,   73,    0,    0,   76,   66,   68,
        0,   68,    0,  345,  247,  252,   88,  255,  260,   50,
      265,  267,  272
    } ;

static yyconst short int yy_def[264] =
    {   0,
      254,    1,  255,  255,  254,  254,  254,  256,  257,  254,
      254,  254,  254,  254,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  254,  254,
      254,  254,  254,  256,  254,  259,  254,  254,  254,  254,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  254,  260,  261,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  262,  263,  258,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  262,  263,  133,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,    0,  254,  254,  254,  254,  254,  254,
      254,  254,  254
    } ;

static yyconst short int yy_nxt[384] =
    {   0,
        6,    7,    7,    8,    9,   10,   11,    6,   12,   13,
       14,   15,    6,   15,   16,   17,   18,   19,   20,   21,
       15,   22,   15,   15,   15,   23,   15,   24,   25,   26,
       27,   28,   15,   15,   15,   15,   29,   30,    6,    6,
       33,   33,   46,   32,   32,   38,   39,   38,   39,   43,
       47,   48,   52,   55,   96,   44,   53,   56,   91,   59,
       54,   60,   63,   33,   33,   64,   38,   39,   65,   81,
       49,   85,   82,   92,   86,   61,   62,   67,   67,  141,
       67,   67,   67,   67,   67,   67,   67,  146,  179,   67,
      177,  147,   36,  178,  253,  252,  251,  250,  142,  249,

      248,  247,  246,  180,  245,  244,  243,  242,  241,  240,
      239,  238,  237,   67,   67,   67,   67,  236,   67,   67,
       67,   67,   67,   67,   67,   68,  235,   67,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,   67,   67,  102,  103,  104,  211,  105,  106,  210,
      107,  209,  208,  207,  108,  206,  109,  110,  205,  111,
      112,   67,   67,  204,   67,   67,   67,   67,   67,   67,
       67,  133,  203,   67,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,

      186,  185,  184,  183,  182,  181,  176,   67,   67,   67,
       67,  175,   67,   67,   67,   67,   67,   67,   67,  133,
      174,   67,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  153,  152,  151,   67,   67,   31,   31,   31,
       31,   31,   34,   34,   34,   34,   34,   41,   41,   41,
       68,  150,   68,   68,   68,   97,  149,   97,   97,   97,
      132,  132,  134,  148,  134,  134,  134,  145,  144,  143,
      140,  139,  138,  137,  136,  135,  131,  130,  129,  128,
      127,  126,  125,  124,  123,  122,  121,  120,  119,  118,

      117,  116,  115,  114,  113,  101,  100,   99,   98,   95,
       94,   93,   90,   89,   88,   87,   84,   83,   80,   79,
       78,   77,   76,   75,   74,   73,   72,   71,   70,   69,
       40,   40,   35,   66,   58,   57,   51,   50,   45,   42,
       40,   37,   35,  254,    5,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254
    } ;

static yyconst short int yy_chk[384] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        7,    7,   19,    3,    4,   12,   12,   14,   14,   17,
       19,   20,   23,   24,  260,   17,   23,   24,   62,   27,
       23,   27,   28,   33,   33,   28,   39,   39,   28,   54,
       20,   57,   54,   62,   57,   27,   27,   36,   36,  105,
       36,   36,   36,   36,   36,   36,   36,  109,  149,   36,
      148,  109,  257,  148,  252,  250,  249,  248,  105,  245,

      243,  242,  241,  149,  239,  237,  236,  235,  232,  228,
      227,  224,  223,   36,   36,   68,   68,  222,   68,   68,
       68,   68,   68,   68,   68,   68,  221,   68,  219,  218,
      217,  215,  214,  213,  212,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  199,  198,  197,  195,  194,
      191,   68,   68,   73,   73,   73,  190,   73,   73,  189,
       73,  187,  183,  181,   73,  180,   73,   73,  179,   73,
       73,   97,   97,  178,   97,   97,   97,   97,   97,   97,
       97,   97,  177,   97,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  164,  163,  162,  161,  159,  158,

      156,  155,  154,  153,  151,  150,  147,   97,   97,  133,
      133,  146,  133,  133,  133,  133,  133,  133,  133,  133,
      145,  133,  144,  143,  142,  141,  140,  139,  138,  137,
      135,  130,  129,  128,  127,  125,  124,  123,  122,  121,
      120,  119,  117,  116,  115,  133,  133,  255,  255,  255,
      255,  255,  256,  256,  256,  256,  256,  258,  258,  258,
      259,  112,  259,  259,  259,  261,  111,  261,  261,  261,
      262,  262,  263,  110,  263,  263,  263,  108,  107,  106,
      104,  103,  102,  101,  100,   99,   95,   94,   93,   92,
       91,   90,   88,   87,   86,   85,   84,   83,   82,   80,

       78,   77,   76,   75,   74,   72,   71,   70,   69,   65,
       64,   63,   61,   60,   59,   58,   56,   55,   53,   52,
       51,   50,   49,   48,   47,   46,   45,   44,   43,   42,
       40,   38,   34,   32,   26,   25,   22,   21,   18,   16,
       13,   10,    8,    5,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
#define INITIAL 0
#line 2 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
#include <stdio.h>
#include <string.h>
#include <string>
//#include "y.tab.h"
#include "parser.hpp"

int yycolumn = 0;
#define YY_USER_ACTION yylloc.first_line = yylloc.last_line = yylineno; \
    yylloc.first_column = yycolumn; yylloc.last_column = yycolumn + yyleng - 1; \
    yycolumn += yyleng;

#define MULTI_COMMENT 1

#line 591 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 17 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"

#line 744 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 255 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 345 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 18 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return COMMENT;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 19 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
{ BEGIN(MULTI_COMMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 20 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 21 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 22 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
yylval.string=yytext; return NUMBER;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 23 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
yylval.string=strdup(yytext); return BANK_EXPR;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 24 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return EXPR;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 25 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return OFFSET;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 26 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_OFFSET;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 27 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return MIN;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 28 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return MAX;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 29 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return STEP;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return SURFACE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 31 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_SURFACE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 32 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return BEG_POINT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 33 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return COLOR;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 34 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_POINT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 35 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return BANK;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 36 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_BANK;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 37 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return SET;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 38 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return FACE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 39 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_FACE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 40 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return OBJECT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 41 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_OBJECT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 42 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return MESH;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 43 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_MESH;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 44 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return TUNNEL;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 45 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_TUNNEL;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 46 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return FUNNEL;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 47 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_FUNNEL;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 48 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return POLYLINE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 49 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return CIRCLE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 50 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_CIRCLE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 51 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return SCALE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 52 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_POLYLINE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 53 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return INSTANCE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 54 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_INSTANCE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 55 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return TRANSLATE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 56 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return ROTATE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 57 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return MIRROR;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 58 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return BEG_DELETE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 59 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_DELETE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 60 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return GROUP;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 61 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_GROUP;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 62 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return SUBDIVISION;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 63 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return END_SUBDIVISION;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 64 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return SUBDIVISIONS;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 65 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return TYPE;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 66 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return OBRACE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 67 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return EBRACE;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 68 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
yylval.string=strdup(yytext); return VARIABLE;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 69 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return OPARENTHESES;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 70 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
return EPARENTHESES;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 71 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
/* ignore whitespace */;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 72 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"
ECHO;
	YY_BREAK
#line 1110 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(MULTI_COMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 255 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 255 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 254);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 72 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\lexer.l"

