// example: class constructor

#include "Lewis/Session.h"
//#include "compilerNome\parser.hpp"
//#include "compilerNome/lexer.h"

// This header is generated by bison.
//#include "compilerNome/parser.hpp"

using namespace std;

class NOMECompiler {
  Session* currSession;
  public:
    NOMECompiler (string input) {
        //currSession->saveFileToStr(input);
        //nomin = fopen(input.c_str(), "r");
        //currSession = createSession();
        //nomparse(currSession);
    };

    Session* getSession () {return currSession;}
};
