//#include "parser.cpp"
//#include "lexer.cpp"
#include "nomeparser.h"


//namespace parserNom
//{
// This header is generated by Flex.
#include "lexer.cpp"

// This header is generated by bison.
#include "parser.cpp"
//}

//#include "lexerStl.cpp"

// This header is generated by bison.
//#include "parserStl.cpp"

NomeParser::NomeParser()
{

}

Session* NomeParser::makeWithNome(vector<ParameterBank> &banks,
                              unordered_map<string, Parameter> &params,
                              Group &group,
                              string input,
                              vector<string> &colorlines,
                              vector<string> &banklines,
                              vector<string> &geometrylines,
                              vector<int> &postProcessingLines,
                              vector<string> &postProcessingLinesString,
                              unordered_map<string, Vertex*> &global_vertices, unordered_map<string, Face*> &global_faces)
{
    currSession->saveFileToStr(input);
    nomin = fopen(input.c_str(), "r");
    nomparse();

    return currSession;
}

