#line 2 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.cpp"

#line 4 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer nom_create_buffer
#define yy_delete_buffer nom_delete_buffer
#define yy_flex_debug nom_flex_debug
#define yy_init_buffer nom_init_buffer
#define yy_flush_buffer nom_flush_buffer
#define yy_load_buffer_state nom_load_buffer_state
#define yy_switch_to_buffer nom_switch_to_buffer
#define yyin nomin
#define yyleng nomleng
#define yylex nomlex
#define yylineno nomlineno
#define yyout nomout
#define yyrestart nomrestart
#define yytext nomtext
#define yywrap nomwrap
#define yyalloc nomalloc
#define yyrealloc nomrealloc
#define yyfree nomfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE nomrestart(nomin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t nomleng;

extern FILE *nomin, *nomout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE nomlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-nomlineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < nomleng; ++yyl )\
                    if ( nomtext[yyl] == '\n' )\
                        --nomlineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up nomtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up nomtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via nomrestart()), so that the user can continue scanning by
	 * just pointing nomin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when nomtext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t nomleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow nomwrap()'s to do buffer switches
 * instead of setting up a fresh nomin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void nomrestart (FILE *input_file  );
void nom_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE nom_create_buffer (FILE *file,int size  );
void nom_delete_buffer (YY_BUFFER_STATE b  );
void nom_flush_buffer (YY_BUFFER_STATE b  );
void nompush_buffer_state (YY_BUFFER_STATE new_buffer  );
void nompop_buffer_state (void );

static void nomensure_buffer_stack (void );
static void nom_load_buffer_state (void );
static void nom_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER nom_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE nom_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE nom_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE nom_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *nomalloc (yy_size_t  );
void *nomrealloc (void *,yy_size_t  );
void nomfree (void *  );

#define yy_new_buffer nom_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        nomensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nom_create_buffer(nomin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        nomensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nom_create_buffer(nomin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define nomwrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *nomin = (FILE *) 0, *nomout = (FILE *) 0;

typedef int yy_state_type;

extern int nomlineno;

int nomlineno = 1;

extern char *nomtext;
#define yytext_ptr nomtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up nomtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	nomleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[299] =
    {   0,
        0,    0,    0,    0,   62,   61,   60,   61,   61,   58,
       59,   61,   61,    5,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   55,   56,
        4,    4,   60,    1,    1,    0,    2,    0,    5,    5,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,    3,
        0,    0,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   17,   57,   16,   57,   57,
       57,   57,   57,   57,   57,   26,   57,   57,   57,   57,

       57,   57,   57,    6,    6,   24,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,    7,   27,   57,   57,   57,   31,   57,
       57,   57,   57,   57,   57,   57,   57,   18,   57,   57,
       57,   57,   54,    6,    6,    6,   57,   57,   57,   57,
       22,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   49,   57,
       57,   57,   57,   21,   57,   57,   40,   57,   57,   57,
       57,   57,   57,   57,   38,   10,   47,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   35,   57,   46,   29,   14,   57,
       45,   11,   57,   57,   57,   33,   57,   57,   25,   57,
       57,   57,   57,   28,   57,   57,   57,   32,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   19,   57,
       57,    8,   57,   57,   57,   57,   57,   50,   57,   57,
       57,   23,   57,   57,   57,   57,   42,   37,   57,   57,
       57,   57,   57,   39,   48,   36,   57,   30,   15,   57,
       57,   57,   34,   57,   44,   57,   57,   57,   57,   57,
       57,   20,   57,   12,   57,    9,   43,   41,   57,   51,
       57,   57,   53,   57,   57,   13,   52,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    1,    1,    1,    6,
        7,    8,    9,    1,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
        1,    1,    1,    1,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,    1,    1,    1,   13,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   12,   30,   31,   32,   33,   34,   12,   35,
       36,   37,   38,    1,   39,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[40] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        4,    5,    3,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1
    } ;

static yyconst flex_int16_t yy_base[308] =
    {   0,
        0,    0,   37,   38,  391,  392,   40,  387,    0,  381,
      392,   37,  377,   39,    0,   37,   31,  369,   17,   40,
      356,  358,   43,   43,  356,  355,   51,   30,  392,  392,
      392,  375,   68,  378,  392,   84,  392,  369,   64,  368,
        0,  351,  340,  347,  345,  346,  348,  347,  354,  341,
      353,  341,  339,  335,  330,  333,   50,  340,  343,   56,
      329,  346,  327,  336,  339,   49,  342,  328,  325,  392,
        0,  123,  329,  330,  326,  334,  318,  320,  329,  148,
      316,  327,  317,  310,  310,    0,  320,    0,  310,  321,
      307,  310,  300,  321,  309,    0,  317,  303,  314,  311,

      302,  301,  309,    0,  180,    0,  308,  303,  299,  305,
      292,  289,   81,  298,  301,   68,  288,  290,  298,   81,
      287,  281,  280,    0,    0,  294,  282,  296,    0,  281,
      292,  289,  274,  280,  272,  285,  284,    0,  279,  286,
      268,  280,    0,    0,  219,    0,  267,  269,  277,  277,
        0,  275,  265,  254,  261,  259,  260,  262,  246,  228,
      224,  223,  230,  233,   80,   57,  224,  225,    0,  222,
      218,  215,  214,    0,  223,  226,    0,  212,  208,  225,
      215,  214,  222,  219,    0,    0,    0,  212,  213,  209,
      217,  213,  204,  190,  183,  183,  193,  195,  181,  184,

      174,  192,  189,  180,    0,  190,    0,    0,    0,  178,
        0,    0,  182,  185,  188,    0,  168,  189,    0,  181,
      176,  172,  164,    0,  177,  165,  178,    0,  167,  160,
      143,  148,  150,  157,  151,  148,  142,  128,    0,  126,
      127,  145,  125,  127,  135,  134,  126,    0,  123,  117,
      116,    0,  125,  112,  129,  119,    0,    0,  121,  124,
      107,  124,  121,    0,    0,    0,  122,    0,    0,  110,
      113,  108,    0,   93,    0,  102,   86,  107,   99,   98,
       84,    0,   87,    0,   83,  100,    0,    0,   88,   78,
       74,   79,    0,   88,   77,    0,    0,  392,  258,  263,

       98,  266,  271,   93,  276,  278,  283
    } ;

static yyconst flex_int16_t yy_def[308] =
    {   0,
      298,    1,  299,  299,  298,  298,  298,  300,  301,  298,
      298,  298,  298,  298,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  298,  298,
      298,  298,  298,  300,  298,  303,  298,  298,  298,  298,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  298,
      304,  305,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302,  306,  307,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  306,  307,  145,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,    0,  298,  298,

      298,  298,  298,  298,  298,  298,  298
    } ;

static yyconst flex_int16_t yy_nxt[432] =
    {   0,
        6,    7,    7,    8,    9,   10,   11,    6,   12,   13,
       14,   15,    6,   15,   16,   17,   18,   19,   20,   21,
       15,   22,   15,   15,   15,   23,   15,   24,   25,   26,
       27,   28,   15,   15,   15,   15,   15,   29,   30,    6,
        6,   33,   33,   49,   32,   32,   38,   39,   38,   39,
       42,   50,   45,   51,   43,   46,   55,   58,   47,   67,
       56,   59,   68,   99,   57,   69,   62,   44,   63,   33,
       33,  202,   52,   38,   39,   64,   88,   92,  100,   89,
       93,  158,   65,   66,   71,   71,  203,   71,   71,   71,
       71,   71,   71,   71,  153,  163,   71,  104,  154,  164,

      159,  200,   36,  297,  201,  296,  295,  294,  293,  292,
      286,  155,  291,  290,  289,  288,  287,  286,  285,  284,
      283,   71,   71,   71,   71,  282,   71,   71,   71,   71,
       71,   71,   71,   72,  281,   71,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  242,  261,  260,  259,  258,
       71,   71,  113,  114,  115,  257,  116,  117,  256,  118,
      255,  254,  253,  119,  252,  120,  121,  251,  122,  123,
       71,   71,  250,   71,   71,   71,   71,   71,   71,   71,
      145,  249,   71,  248,  247,  246,  245,  244,  243,  242,

      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,   71,   71,   71,
       71,  224,   71,   71,   71,   71,   71,   71,   71,  145,
      223,   71,  222,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  199,  198,  197,  196,  195,   71,   71,   31,   31,
       31,   31,   31,   34,   34,   34,   34,   34,   41,   41,
       41,   72,  194,   72,   72,   72,  105,  193,  105,  105,
      105,  144,  144,  146,  192,  146,  146,  146,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  162,  161,  160,  157,  156,
      152,  151,  150,  149,  148,  147,  143,  142,  141,  140,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  112,  111,  110,  109,
      108,  107,  106,  103,  102,  101,   98,   97,   96,   95,
       94,   91,   90,   87,   86,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   73,   40,   40,
       35,   70,   61,   60,   54,   53,   48,   40,   37,   35,
      298,    5,  298,  298,  298,  298,  298,  298,  298,  298,

      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298
    } ;

static yyconst flex_int16_t yy_chk[432] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    7,    7,   19,    3,    4,   12,   12,   14,   14,
       16,   19,   17,   20,   16,   17,   23,   24,   17,   28,
       23,   24,   28,   66,   23,   28,   27,   16,   27,   33,
       33,  166,   20,   39,   39,   27,   57,   60,   66,   57,
       60,  116,   27,   27,   36,   36,  166,   36,   36,   36,
       36,   36,   36,   36,  113,  120,   36,  304,  113,  120,

      116,  165,  301,  295,  165,  294,  292,  291,  290,  289,
      286,  113,  285,  283,  281,  280,  279,  278,  277,  276,
      274,   36,   36,   72,   72,  272,   72,   72,   72,   72,
       72,   72,   72,   72,  271,   72,  270,  267,  263,  262,
      261,  260,  259,  256,  255,  254,  253,  251,  250,  249,
      247,  246,  245,  244,  243,  242,  241,  240,  238,  237,
       72,   72,   80,   80,   80,  236,   80,   80,  235,   80,
      234,  233,  232,   80,  231,   80,   80,  230,   80,   80,
      105,  105,  229,  105,  105,  105,  105,  105,  105,  105,
      105,  227,  105,  226,  225,  223,  222,  221,  220,  218,

      217,  215,  214,  213,  210,  206,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  105,  105,  145,
      145,  193,  145,  145,  145,  145,  145,  145,  145,  145,
      192,  145,  191,  190,  189,  188,  184,  183,  182,  181,
      180,  179,  178,  176,  175,  173,  172,  171,  170,  168,
      167,  164,  163,  162,  161,  160,  145,  145,  299,  299,
      299,  299,  299,  300,  300,  300,  300,  300,  302,  302,
      302,  303,  159,  303,  303,  303,  305,  158,  305,  305,
      305,  306,  306,  307,  157,  307,  307,  307,  156,  155,
      154,  153,  152,  150,  149,  148,  147,  142,  141,  140,

      139,  137,  136,  135,  134,  133,  132,  131,  130,  128,
      127,  126,  123,  122,  121,  119,  118,  117,  115,  114,
      112,  111,  110,  109,  108,  107,  103,  102,  101,  100,
       99,   98,   97,   95,   94,   93,   92,   91,   90,   89,
       87,   85,   84,   83,   82,   81,   79,   78,   77,   76,
       75,   74,   73,   69,   68,   67,   65,   64,   63,   62,
       61,   59,   58,   56,   55,   54,   53,   52,   51,   50,
       49,   48,   47,   46,   45,   44,   43,   42,   40,   38,
       34,   32,   26,   25,   22,   21,   18,   13,   10,    8,
        5,  298,  298,  298,  298,  298,  298,  298,  298,  298,

      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[62] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int nom_flex_debug;
int nom_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *nomtext;
#line 1 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
#line 3 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
#include <stdio.h>
#include <string.h>
#include <string>
#include "parser.hpp"

int nomcolumn = 0;
#define nom_USER_ACTION nomlloc.first_line = nomlloc.last_line = nomlineno; \
    nomlloc.first_column = nomcolumn; nomlloc.last_column = nomcolumn + nomleng - 1; \
    nomcolumn += nomleng;


#line 701 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.cpp"

#define INITIAL 0
#define MULTI_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int nomlex_destroy (void );

int nomget_debug (void );

void nomset_debug (int debug_flag  );

YY_EXTRA_TYPE nomget_extra (void );

void nomset_extra (YY_EXTRA_TYPE user_defined  );

FILE *nomget_in (void );

void nomset_in  (FILE * in_str  );

FILE *nomget_out (void );

void nomset_out  (FILE * out_str  );

yy_size_t nomget_leng (void );

char *nomget_text (void );

int nomget_lineno (void );

void nomset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int nomwrap (void );
#else
extern int nomwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( nomtext, nomleng, 1, nomout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( nomin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( nomin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, nomin))==0 && ferror(nomin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(nomin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int nomlex (void);

#define YY_DECL int nomlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after nomtext and nomleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 21 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"

#line 886 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! nomin )
			nomin = stdin;

		if ( ! nomout )
			nomout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			nomensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				nom_create_buffer(nomin,YY_BUF_SIZE );
		}

		nom_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of nomtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 299 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 392 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < nomleng; ++yyl )
				if ( nomtext[yyl] == '\n' )
					   
    nomlineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 22 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return COMMENT;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
{ BEGIN(MULTI_COMMENT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
nomlval.string=nomtext; return NUMBER;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
nomlval.string=strdup(nomtext); return BANK_EXPR;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return EXPR;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
nomlval.intNumber = std::stoi(std::string(nomtext).substr (7)); return BSPLINE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
nomlval.intNumber = std::stoi(std::string(nomtext).substr (10)); return END_BSPLINE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return CLOSED;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return SLICES;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return BEZIERCURVE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_BEZIERCURVE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return OFFSET;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_OFFSET;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return MIN;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return MAX;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return STEP;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return SURFACE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_SURFACE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return BEG_POINT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return COLOR;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_POINT;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return BANK;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_BANK;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return SET;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return FACE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_FACE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return OBJECT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_OBJECT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return MESH;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_MESH;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return TUNNEL;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_TUNNEL;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return FUNNEL;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_FUNNEL;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return POLYLINE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return CIRCLE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_CIRCLE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return SCALE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_POLYLINE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return INSTANCE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_INSTANCE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return TRANSLATE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return ROTATE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return MIRROR;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return BEG_DELETE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_DELETE;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return GROUP;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_GROUP;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return SUBDIVISION;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return END_SUBDIVISION;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return SUBDIVISIONS;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return TYPE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return OBRACE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return EBRACE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
nomlval.string=strdup(nomtext); return VARIABLE;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return OPARENTHESES;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
return EPARENTHESES;
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 81 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
/* ignore whitespace */;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"
ECHO;
	YY_BREAK
#line 1286 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MULTI_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed nomin at a new source and called
			 * nomlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = nomin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( nomwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * nomtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of nomlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					nomrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			nomrestart(nomin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) nomrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 299 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 299 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 298);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up nomtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --nomlineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					nomrestart(nomin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( nomwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve nomtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    nomlineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void nomrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        nomensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            nom_create_buffer(nomin,YY_BUF_SIZE );
	}

	nom_init_buffer(YY_CURRENT_BUFFER,input_file );
	nom_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void nom_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		nompop_buffer_state();
	 *		nompush_buffer_state(new_buffer);
     */
	nomensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	nom_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (nomwrap()) processing, but the only time this flag
	 * is looked at is after nomwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void nom_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	nomin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE nom_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) nomalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nom_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) nomalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in nom_create_buffer()" );

	b->yy_is_our_buffer = 1;

	nom_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with nom_create_buffer()
 * 
 */
    void nom_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		nomfree((void *) b->yy_ch_buf  );

	nomfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a nomrestart() or at EOF.
 */
    static void nom_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	nom_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then nom_init_buffer was _probably_
     * called from nomrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void nom_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		nom_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void nompush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	nomensure_buffer_stack();

	/* This block is copied from nom_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from nom_switch_to_buffer. */
	nom_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void nompop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	nom_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		nom_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void nomensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)nomalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in nomensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)nomrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in nomensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE nom_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) nomalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nom_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	nom_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to nomlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       nom_scan_bytes() instead.
 */
YY_BUFFER_STATE nom_scan_string (yyconst char * yystr )
{
    
	return nom_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to nomlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE nom_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) nomalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in nom_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = nom_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in nom_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up nomtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		nomtext[nomleng] = (yy_hold_char); \
		(yy_c_buf_p) = nomtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		nomleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int nomget_lineno  (void)
{
        
    return nomlineno;
}

/** Get the input stream.
 * 
 */
FILE *nomget_in  (void)
{
        return nomin;
}

/** Get the output stream.
 * 
 */
FILE *nomget_out  (void)
{
        return nomout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t nomget_leng  (void)
{
        return nomleng;
}

/** Get the current token.
 * 
 */

char *nomget_text  (void)
{
        return nomtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void nomset_lineno (int  line_number )
{
    
    nomlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see nom_switch_to_buffer
 */
void nomset_in (FILE *  in_str )
{
        nomin = in_str ;
}

void nomset_out (FILE *  out_str )
{
        nomout = out_str ;
}

int nomget_debug  (void)
{
        return nom_flex_debug;
}

void nomset_debug (int  bdebug )
{
        nom_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from nomlex_destroy(), so don't allocate here.
     */

    /* We do not touch nomlineno unless the option is enabled. */
    nomlineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    nomin = stdin;
    nomout = stdout;
#else
    nomin = (FILE *) 0;
    nomout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * nomlex_init()
     */
    return 0;
}

/* nomlex_destroy is for both reentrant and non-reentrant scanners. */
int nomlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		nom_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		nompop_buffer_state();
	}

	/* Destroy the stack itself. */
	nomfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * nomlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *nomalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *nomrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void nomfree (void * ptr )
{
	free( (char *) ptr );	/* see nomrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 81 "C:\\Users\\dieppedalle\\Documents\\nomeProject\\nome\\compilerNome\\lexer.l"



